version: '3'
 
services:
  bind9:
    image: ubuntu/bind9
    container_name: dns
    environment:
      - BIND9_USER=root
      - TZ=Canada/Pacific
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped   
